Long arithmetics and quad trees
AndreiZaycev/Semester pull request #12
Opened 2021-01-22 06:50 UTC by AndreiZaycev

2021-02-06 08:41 UTC, gsvgit requested changes
Над матрицами надо подумать. А длинную арифметику, кажется, уже проще переделать. Там ад какой-то.

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +    | Leaf of 't
Дерево явоно избыточное. Зачем в узлах инты? почему в листьях какие-то тройки?

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        match x, y with
Перемудрили. Можно существенно меньше вариантов расматривать.

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +    let outputTree = create (generatorOneValue (dim x) (dim x) 1)
Можно существенно проще, без циклов и прочего.

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +    let outputTree = create (generatorOneValue (dim x) (dim x) 1)
Подумайте об умножении блочных матриц.

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +    let rec _go x =
Тоже можно проще, без вычисления размеров и прочего шаманства.

2021-02-06 08:41 UTC, gsvgit commented on src/MyList/Listik.fs
> +let tail x = // хитрый хвост листа, который для последнего элемента возвращает One 0
Ну тогда это не tail

2021-02-06 08:41 UTC, gsvgit commented on src/MyList/Listik.fs
> +let head x = // голова листа
А зачем такие комментарии? Из названия не понятно, что делает функция? Значит навание плохое.

2021-02-06 08:41 UTC, gsvgit commented on src/MyList/Listik.fs
> +let rec map2 f acc x y = // map2
А почему у map2 аккумулятор наружу торчит?

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +        let compareInt x y = if x = max x y then true else false
Вот сколько можно. Давайте ещё минус балл. -3 уже, кажется.

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +let equals x y =
А может просто compare написать?

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +    if flag = true
Огонь!

2021-02-06 08:41 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +let multiply fList sList =
Жесть какая-то.

2021-02-06 08:44 UTC, AndreiZaycev commented on src/UseLibrary/QuadTree.fs
> +    | Leaf of 't
В узлах хранится еще и размерность, а тройка это координаты и данные

2021-02-06 08:46 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +    | Leaf of 't
Это избыточная информация. Всё это однозначно определяется положением узла в дереве.

2021-02-11 07:18 UTC, gsvgit requested changes

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +let toDefoltList x =
Думается мне, что не default, а System, скорее.

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +    let mutable firstElem =
Хм. Сдаётся мне, что если индекс не корректен, то Вы получите тут странный результат.

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +       | One t -> failwith "list length is not suitable"
Форматирование.

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +let specialTail x = // хитрый хвост листа, который для последнего элемента возвращает One 0
tailOrZero ?

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +       | One t -> One 0
Форматирование?

2021-02-11 07:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +let map2 f x y = // map2
Классный комментарий!

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +let private detect x = if x = 1 then Positive elif x = -1 then Negative else failwith "error"
Исчерпывающее сообщение об ошибке!

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +let absolute x = BigInt (1, x)
Что это?

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +    match k with
Эм.... Это Вы так ```if k =1 ``` написали?

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +let compareDigits x y =
А сравниваем мы здесь, кажется, числа, а не цифры.

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +        | One 0 -> One 0
А чем первые два варианта отличаются?

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/BigAriphmetics.fs
> +            match k with
И снова странный if

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/ExtendedMatrix.fs
> +    new (x, y, data) = {inherit Pair(x * 1<Row>, y * 1<Col>); data = data}
Я бы требовал, чтобы сюда сразу правильные координаты предовались. Иначе мало смысла в происходящем.

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +            // тут на тестах some troubles, приходится честно проверять что если Node (None, None, None, None)
Вообще, достаточно ожидаемо. Пустые поддеревья надо редуцировать.

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        | Leaf t, Leaf k -> Leaf (t * k)
Вот здесь, кажется, неплохо бы на ноль проверить.

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        | Leaf k, Leaf t -> Leaf (k + t)
Вот здесь, кажется, неплохо бы на ноль проверить.

2021-02-11 07:18 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +module QuadTree
Вообще, лучше сразу делайте параметризацию полукольцом. Всё равно для автоматов потребуется.

2021-02-11 07:18 UTC, gsvgit commented on tests/UseLibrary.Tests/LongArithmetics.fs
> +let shablon valuesTest operator (operator1: BigInt -> BigInt -> BigInt) name =
template :)

2021-02-11 07:24 UTC, AndreiZaycev commented on src/UseLibrary/BigAriphmetics.fs
> +let absolute x = BigInt (1, x)
по модулю иногда числа удобно рассматривать. это модуль бигинт

2021-02-13 18:04 UTC, gsvgit requested changes

2021-02-13 18:04 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
И вот смотрите, какая проблема: функция "multiplyScalar", а достаёте Вы из моноида "sum".

2021-02-13 18:04 UTC, gsvgit commented on tests/UseLibrary.Tests/Quads.fs
> +let iDontKnowHowToNameIt =
Надо всё же придумать что-то вменяемое.

2021-02-13 18:06 UTC, AndreiZaycev commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
я тоже над этим думал, то есть пытаться придумать какое-то лучшее название для поля моноида?

2021-02-13 18:07 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
Или лучшую структуру абстракций. Может не надо всё явно в группу пихать. Или ещё что.

2021-02-13 18:14 UTC, AndreiZaycev commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
кажется что мой вариант более быстро реализуем :)

2021-02-13 18:15 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
Такой себе аргумент)

2021-02-13 18:17 UTC, AndreiZaycev commented on src/UseLibrary/QuadTree.fs
> +        | Monoid x -> x.neutral, x.sum
:(

2021-02-15 10:06 UTC, gsvgit requested changes
Выглядит так, будто процесс сходится.

2021-02-15 10:06 UTC, gsvgit commented on src/UseLibrary/Group.fs
> +type Group<'t> =
Правда ли, что везде, где надо, есть обратные, чтобы действительно группа была?

2021-02-15 10:06 UTC, gsvgit commented on src/UseLibrary/Group.fs
> +type Monoid<'t> =
А правда ли, что наличие слодения нельзя потребовать через ограаничение на тип?

2021-02-15 10:06 UTC, gsvgit commented on src/UseLibrary/QuadTree.fs
> +            if first = None && second = None && third = None && fourth = None
Кажется, дублируется с тем, что в сложении делаете.

2021-02-21 19:06 UTC, AndreiZaycev commented on src/UseLibrary/QuadTree.fs
> +            if first = None && second = None && third = None && fourth = None
Сама проверка если только, а выражать ее более громоздко кажется

2021-02-27 18:49 UTC, gsvgit commented on src/UseLibrary/SparseMatrix.fs
> +    if x.numOfCols <> y.numOfCols && y.numOfRows <> x.numOfRows
Что-то у Вас какая-то каша с разреженными матрицами. Почему бы не работать с матрицами в формате дерева квадрантов? Один раз сконвертировали в этот формат, дальше работаете с ним. Зачем гонять туда-обратно?

2021-02-28 08:38 UTC, AndreiZaycev commented on src/UseLibrary/SparseMatrix.fs
> +    if x.numOfCols <> y.numOfCols && y.numOfRows <> x.numOfRows
Я подумал будет очень удобно в автоматах просто юзать нашу спарс матрицу, складывать в виде квадродеревьев и обратно получать матрицу

2021-02-28 08:39 UTC, AndreiZaycev commented on src/UseLibrary/SparseMatrix.fs
> +    if x.numOfCols <> y.numOfCols && y.numOfRows <> x.numOfRows
Вместо того, чтобы каждый раз обходить дерево для поиска той самой даты, которая может удобно храниться в листе у спарс матрицы

2021-02-28 17:52 UTC, gsvgit commented on src/UseLibrary/SparseMatrix.fs
> +    val specialSize: int
Это что за зверь?

2021-02-28 17:52 UTC, gsvgit commented on src/UseLibrary/SparseMatrix.fs
> +                | None, _ -> None
Можно объединить в один:
```
| None, _ | _, None -> None
```

2021-02-28 19:13 UTC, AndreiZaycev commented on src/UseLibrary/SparseMatrix.fs
> +    val specialSize: int
Это, если так можно выразиться, размер округленный до степени двойки

2021-02-28 19:19 UTC, AndreiZaycev commented on src/UseLibrary/SparseMatrix.fs
> +    val specialSize: int
Через конструктор всегда сам определяется, выглядит удобно, но если он излишен, уберу

2021-04-07 15:18 UTC, merged