added gui w avalonia
AndreiZaycev/Semester pull request #20
Opened 2021-05-20 17:10 UTC by AndreiZaycev

Добавил гуишку, она билдится, нервы закончились, добавил токен через environment variables

2021-05-21 15:58 UTC, AndreiZaycev commented
Варнинги, что в коде, какие-то непонятные, просят удалить completition window, а без него все падает. Bug...

2021-05-23 14:05 UTC, AndreiZaycev commented
Пофиксил варнинги

2021-06-01 08:04 UTC, gsvgit commented
Запускаем IDE, пишем
```
let x = 5

let y = x + 2

print x
```

Нажимаем Run --- работает, печатает 5.

Ставим точку остановки на 3 строке. Нажимаем Run, получаем в консоль "Syntax error"

2021-06-01 08:09 UTC, gsvgit commented
Пишем
```
let x = 5342345234532432453245324532453245324542342342343245324532453245324532453245

let a = 224353245324532453245324532453245
let y = a - x

let z = y ^ x

print z
``` 
Нажимаем Run и ничего не происходит. Совсем ничего.

2021-06-01 08:13 UTC, gsvgit commented
А ещё я могу написать такой вот код:
```
let c = 2 
Heh, look, this code is correct!
```
Нажать run и ничего не произойдёт. Хотя я бы не сказал, что код корректый.

2021-06-02 12:28 UTC, AndreiZaycev commented
Я похоже пул  реквест с генератором и деревьями замержил сюда...

2021-06-03 09:29 UTC, AndreiZaycev commented
Теперь эта замечательная ветка не содержит никаких изъянов и готова к ревью

2021-06-04 12:49 UTC, gsvgit requested changes

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/ViewModels/ViewModelBase.cs
> +namespace AvaloniaEditDemo.ViewModels
Ой, а зачем Вам этот класс. Он же пустой.

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        flag = true;
А можно флагу дать такое название, чтобы было понятно, за что он отвечает?

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                                _console.Text = "Parse error";
Мммм А можно как-то подробнее узнавать, что там за ошибка? Парсер-то, навреное, сообщит.

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            else
А можно ли эту простыню if-ов как-то разбить на отдельные методы, например?

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            {
Дублирование кода

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    _textEditor.Text = text;
Гы-гы. А я как раз хотел сросить, а что это IDE не запоминает, какой файл я открыл и при сохранении спрашивает.

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    var button = new Button() { Height = 16.8, Width = 20, Background = Brush.Parse("Yellow"), Margin = Thickness.Parse("0,0") };
Ох, сдаётся мне, что как только я увеличу размер шрифта, все эти константы отъедут.

2021-06-04 12:49 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +        class ElementGenerator : VisualLineElementGenerator, IComparer<Pair>
А это что за зверь такой?

2021-08-06 10:55 UTC, AndreiZaycev commented
В ветку много ненужного, надо пофиксить

2021-08-06 14:26 UTC, AndreiZaycev commented
Исправил конфликты в новой ветке 👉 [GuiAvaloniaFixed](https://github.com/AndreiZaycev/Semester/pull/26)
Эту ветку закрываю.

2021-08-06 14:26 UTC, closed without merging