Gui avalonia fixed
AndreiZaycev/Semester pull request #26
Opened 2021-08-06 14:14 UTC by AndreiZaycev

Ветка GuiAvalonia была с лишним кодом, лучшим решением было создать новую ветку без мусора

2021-08-20 05:39 UTC, gsvgit requested changes
Аккуратнее надо быть, аккуратнее.

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            // ��� �������� 2, ������ ��� � ����� ������� ������-�� ������ ������ ����� ������ � 2 ������� ������
Это сто за иероглифы?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            var parsed = Arithm.Main.parse(text);
А в чём смысл делать парсер вне таски?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Класс. А  что за Item3 ?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return null;
Отличная обработка исключительных ситуаций.

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                textToExecute += lines[counter] + " ";
Неужели в C# ещё не завезли срезу массивов и нормальную конкатенацию?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return Arithm.Interpreter.run(parsed).Item2;
Аналогично. Что за Item2 ?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return null;
Обработка исключений.

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        sendMessageToConsole("Failed while parsing");
Очень информативное сообщение.

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            _console.Text += $"{keys[^2..].Replace("\"", "")} = {values}{ Environment.NewLine }";
Что-то вот эти строковые махинации говнокодом попахивают

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            if (_textEditor.Text.Replace(" ", "").Replace($"{Environment.NewLine}", "") == "")
Что?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
Не очень понял. В коде может быть всего одна точка остановки?

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            { }
Отличная обработка исключений!

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                { }
Отличная обработка исключений!

2021-08-20 05:39 UTC, gsvgit commented on src/AvaloniaEditDemo/highlighter.xshd
> +            \b0[xX][0-9a-fA-F]+  # hex number
Сразу видно, что схема подсветки специально для Вашего языка.

2021-08-20 07:02 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            // ��� �������� 2, ������ ��� � ����� ������� ������-�� ������ ������ ����� ������ � 2 ������� ������
Кодировка крутая

2021-08-20 07:04 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Ну это какая-то реализация интерпретатора, в доке вроде должно быть прописано(я не уверен)

2021-08-20 07:05 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
так может просто сделать нормальные имена полям?

2021-08-20 07:13 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Проблема в том, что пакет чужой, может здесь проще закомментить?

2021-08-20 07:22 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            _console.Text += $"{keys[^2..].Replace("\"", "")} = {values}{ Environment.NewLine }";
keys выглядит примерно так:  "Var x", мне нужно избавиться от Var и убрать кавычки, вроде нет тут 💩

2021-08-20 07:22 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            if (_textEditor.Text.Replace(" ", "").Replace($"{Environment.NewLine}", "") == "")
Здесь проверка на пустой файлик, в котором могли натыкать пробельчиков, энтеров

2021-08-20 07:24 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                textToExecute += lines[counter] + " ";
Согласен, костылек

2021-08-20 07:28 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
Не понял немножко комментарий, Вы имеете ввиду плохое название метода или то что за один ран выполняется одна точка остановки?

2021-08-20 07:31 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
А вот я вообще не понял. Ни то, ни другое. Из кода кажется, что Вы всегда имеете только одну точку остановки, что странно. Я их сколько угодно могу поставить.

2021-08-20 07:32 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            if (_textEditor.Text.Replace(" ", "").Replace($"{Environment.NewLine}", "") == "")
Эм...  Trim ?

2021-08-20 07:33 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Так а что мы обсуждали? Заволите issue и вперёд.

2021-08-20 07:33 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Так а что мы обсуждали? Заволите issue и вперёд.

2021-08-20 07:33 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            _console.Text += $"{keys[^2..].Replace("\"", "")} = {values}{ Environment.NewLine }";
Так сами по себе таки коллекции --- костыль уровня дизайна.

2021-08-20 07:45 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            if (_textEditor.Text.Replace(" ", "").Replace($"{Environment.NewLine}", "") == "")
Не помню почему, но по какой-то причине я его не использовал здесь

2021-08-20 07:48 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
Я сделал брейкпоинты как в визуалке, то есть если их много, то выполняется сначала первая точка остановки, а потом жмется еще раз исполнение и выполняется следующая по очереди

2021-08-20 07:51 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            if (_textEditor.Text.Replace(" ", "").Replace($"{Environment.NewLine}", "") == "")
Пофиксим!

2021-08-20 08:27 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            _console.Text += $"{keys[^2..].Replace("\"", "")} = {values}{ Environment.NewLine }";
И как тут тогда лучше сделать?

2021-08-20 10:35 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
А, тут маленькая ошибочка с моей стороны, Item 3 это 3 элемент кортежа, ран возвращает кортеж из 3 словарей

2021-08-20 10:37 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
А этот кортеж в реализации интерпрететатора нужен был, чтобы не дублировать код

2021-08-20 10:40 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
То есть эти поля системные у кортежей, отвечая на ваш вопрос про смену имен полей

2021-08-20 15:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Так вот. Мы даже обсуждали, что кортежи --- не самая хорошая структура данных. Вы, вот, уже и сами запутались.

2021-08-20 15:43 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
И каждый раз выполняется весь код?

2021-08-20 17:05 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                    return dict.Item3;
Но написать 3 одинаковых обхода синтаксического дерева с разными выводами тоже не лучшая затея, верно?

2021-08-20 17:07 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        executeCodeWithBreakpoint(line);
До определенной точки

2021-08-22 10:19 UTC, AndreiZaycev commented
Также теперь при новом брейкпоинте старый код повторно не выполняется

2021-08-23 08:08 UTC, gsvgit commented
Открываю IDE. НАбираю следующий код:
```
let x = 10
let y = 200
let z = x + y
pront z
```

Говрю Run. Мне говорят, что всё хорошо и Execution finished. Хотя в последней строке ошибка.

Если попробовать исполнить вот такой код
```
let x = 10
let y = 200
let z = x + y
pront z
let z = x * y
print z
```
то тоже скажут, что всё хорошо. При этом ничего напечатано не будет.

Далее.

```





let x = 10
let y = 200
let z = x + y + y
print z
let z = x * y
print z
```

Первые строки пустые. Скажем, первые 5. Ставим точку остановки на 3 строку. Говорим Run, получаем "parse error". Что странно. Код-то у меня корректный.

Отдельный разговор, что parse error вообще не уточняет, где и в чём проблема.


Беру код:
```
let x = 10
let y = 200
let z = x + y + y * x
print z
let z = x * y
print z
```
Ставлю точку остановки на 2 строку. Говорю Run, получаю 
```
Local variables
x = 10
```
Сразу ставлю точнку остановки на 5 строку и говорю Run. Ничего не происходит.

И снова тот же код. Ставлю точку остановки на 2 строку, жму Run, останавливаюсь на точке. Ставлю точку на 6 строку, жму Run два (!) раза, останавливаюсь на 6 строке. Ставлю точку на 4 строке. Жму Run. Получаю 2 активные точки остановки (см картинку).
![Screenshot from 2021-08-23 11-07-02](https://user-images.githubusercontent.com/106816/130412871-92380dd2-beaa-4c41-bce0-c8471364410a.png)

2021-08-23 08:09 UTC, gsvgit commented on src/AvaloniaEditDemo/highlighter.xshd
> +    <RuleSet>
Решили просто удалить числа? Не, так не пойдёт.

2021-08-23 08:24 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/highlighter.xshd
> +    <RuleSet>
ЭХ :trollface:

2021-08-23 11:39 UTC, AndreiZaycev commented
Сделал так, что нельзя ставить новые брейкпоинты, если выполняются старые, пофиксил замечания, поставил хайлайтер для циферок

2021-08-23 11:39 UTC, AndreiZaycev commented
:trollface:

2021-08-24 06:10 UTC, gsvgit commented
> Сделал так, что нельзя ставить новые брейкпоинты, если выполняются старые, пофиксил замечания, поставил хайлайтер для циферок

Не, так не пойдёт. Лучше сразу запретить вообще брейкоинты ставить. Вообще никаких проблем не будет. Это нормальный сценарий --- когда в процессе отлажки пользователь понимает, что надо поставить ещё точки остановки.

2021-08-30 07:17 UTC, gsvgit commented
Смотрите, что могу. Берём код
```







let x = 10
let y = 200
let z = x + y + y
pr0nt z
let z = x * y * y
print z
```
Ставим точки остановки на 11, 12 и 13 строках. Жмём Run. На второй точке мне говорят, что parse error, но если нажать Run, то нормально работаем дальше. Как так?

2021-08-30 10:09 UTC, AndreiZaycev commented
> let x = 10
> let y = 200
> let z = x + y + y
> pr0nt z
> let z = x * y * y
> print z

Oops 😞

2021-08-31 16:26 UTC, AndreiZaycev commented
Сделал привязку брейкпоинтов к строкам с кодом, теперь есть возможность редактирования кода во время дебага, в visual studio не дается никаких комментариев к вставке кода выше исполненного брейкпоинта, вдохновлялся ею, также если во время дебага встречается ошибка, и юзер решает перейти на новый брейкпоинт, то дебаг дропается и начинается с самого начала

2021-09-02 07:08 UTC, gsvgit commented
Берйм код
```
let x = 100
let y = 200
let z = x + y + y
let z = x * y * y ^ y ^ z
print z
```

Говорим Run. Нам говорят, что исполнение начато. Сразу же модифицируем код и снова говорим Run. Всё еще исполнение начато. А ещё можно отладку запустить. Каша какая-то происходит.

2021-09-02 11:55 UTC, gsvgit requested changes
Что-то Ваш код снова всё хуже и хуже. Удалите уже всё и сделайте сначала и аккуратно.

2021-09-02 11:55 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
>          private int counterOfBreakpoint = 0;
Ой, что это?)

2021-09-02 11:55 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                if (_console.Text == "Debug started." || _console.Text == debugMessage)
Что? :hankey:

2021-09-02 12:05 UTC, AndreiZaycev commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                if (_console.Text == "Debug started." || _console.Text == debugMessage)
Не очень понял, почему это 💩

2021-09-02 15:59 UTC, AndreiZaycev commented
Это еще не финальные изменения

2021-09-03 06:33 UTC, gsvgit commented
А зачам Вы разрешаете открывать файл и ставить точки остановки пока программа выполняется? Например, правда ли, что если программа уже начал исполняться и я поставил точку остановки, то исполнение на ней остановится? В Студии такое в некоторых случаях работает, напрмиер.

2021-09-03 07:42 UTC, AndreiZaycev commented
Запретил тыкать на брейкпоинты и кнопки(кроме стопа) во время дебага и пофиксил один баг

2021-09-05 11:42 UTC, gsvgit requested changes

2021-09-05 11:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                                    if (t.Result.VariablesDictionary.Count == 0) _console.Text = $"Local variables are empty.";
Афигенное форматирование. Сами придумали?

2021-09-05 11:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                            if (isSuccessfulRun) { _executionStatus.Background = Brushes.Green; _console.Text += "Execution finished."; }
А здесь уже иначе.

2021-09-05 11:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                        _console.Text = $"Local variables are empty.";
Если строковые литералы несоклько раз используются, надо их выносить в константы.

2021-09-05 11:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +                if (lineOfFirstGreenBreakpoint == -1 && line >= lineOfLinearDebugEnd && button.Background == Brushes.Green) lineOfFirstGreenBreakpoint = line;
Хорошо, нынче у большинства мониторы широкие)

2021-09-05 11:42 UTC, gsvgit commented on src/AvaloniaEditDemo/Views/MainWindow.axaml.cs
> +            openedFileDialog.Filters.Add(new FileDialogFilter() { Name = "Txt", Extensions = { "txt" } });
Сами догадались?)

2021-09-07 07:19 UTC, gsvgit approved these changes
С Вижуалкой сложно сравнивать. Наверное, даже простой блокнот лучше, но для первого раза сойдёт.

2021-09-08 13:33 UTC, merged