parallel quad trees and generator
AndreiZaycev/Semester pull request #27
Opened 2021-09-09 16:07 UTC by AndreiZaycev

2021-09-13 08:48 UTC, gsvgit requested changes

2021-09-13 08:48 UTC, gsvgit commented on src/UseLibrary/Generator.fs
> +    val _steams: int
Опечатка?

2021-09-13 08:48 UTC, gsvgit commented on src/UseLibrary/Main.fs
> +        for i in argv do
Да! Зачам Argu!

2021-09-13 08:48 UTC, gsvgit commented on tests/UseLibrary.Tests/TestsForGenerator.fs
> +                    | _ -> ()
А могли бы просто деление по модулю сделать.

2021-09-13 08:48 UTC, gsvgit commented on tests/UseLibrary.Tests/TestsForGenerator.fs
> +                    | _ -> ()
Ну, точнее, остаток.

2021-09-20 06:41 UTC, gsvgit commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
1) У Вас тут вообще фигня написана. Пожалуй, ещё -3 балла за внимательноть и попытки просто заглушить предупреждения компилятора.
2) http://fsprojects.github.io/Argu/reference/argu-parseresults-1.html#GetResult Ну и вообще, почитайте документацию библиотеки, которой Вы пользуетесь.

2021-09-20 08:56 UTC, AndreiZaycev commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
Так там просто ветвь элс просило я игнор написал

2021-09-20 09:04 UTC, gsvgit commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
Что, простите?

2021-09-20 09:08 UTC, AndreiZaycev commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
![image](https://user-images.githubusercontent.com/71140884/133979062-555ba74d-b3a2-4a8f-b870-d13385faffce.png)
Вы же про этот ignore говорите, я его написал потому что компилятор просил ветвь else написать

2021-09-20 09:57 UTC, gsvgit commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
Да, я про него. И да, я думаю, что понимаю, что хочет компилятор. А вот Вы, кажетмся, нет.

2021-09-20 10:53 UTC, AndreiZaycev commented on src/UseLibrary/Main.fs
> +        then streams = x.GetResult Streams |> ignore
А, я понял, что тут не так. Синтаксисы языков перепутал 😢

2021-09-20 12:22 UTC, AndreiZaycev commented
Забыл дописать исключения при неправильном вводе потоков

2021-10-11 08:44 UTC, gsvgit commented on src/UseLibrary/SparseMatrix.fs
> +    static member Multiply group (tree: QuadTreeMatrix<'t>) (tree1: QuadTreeMatrix<'t>) =
И всё же. Почему это статические члены класса? Раз уж они не зависят от инстанса, то почему не просто функции?

2021-10-11 08:46 UTC, gsvgit requested changes
Ещё есть пара вопросов.

2021-10-18 10:03 UTC, gsvgit reviewed
Вы, кажется, опять намешали всё в кучу. Это какая домашка?

2021-10-23 10:15 UTC, gsvgit approved these changes
Ну, допустим.

2021-10-23 16:16 UTC, merged