mailbox
AndreiZaycev/Semester pull request #29
Opened 2021-10-12 21:50 UTC by AndreiZaycev

2021-10-18 08:59 UTC, gsvgit requested changes

2021-10-18 08:59 UTC, gsvgit commented on MailBox/Balancer.fs
> +    for i in 0 .. mtx.GetLength(0) - 1 do
Что-то мне кажется, что по двухмерным массивам какой-нибудь fold тоже есть.

2021-10-18 08:59 UTC, gsvgit commented on MailBox/Balancer.fs
> +                        | ArrayStandart -> arrayParallel.Post pair
Больше параллельности даже там, где она не нужна!

2021-10-18 08:59 UTC, gsvgit commented on MailBox/Config.fs
> +    val SparsityBound: float
А Вы только по разреженности определяете? А рвзмеры не влияют на производительность?

2021-10-18 08:59 UTC, gsvgit commented on MailBox/Loader.fs
> +let read path =
:hankey:

2021-10-18 08:59 UTC, gsvgit commented on MailBox/Multiplier.fs
> +let arrayParallelMultiply (mtx1: int[,]) (mtx2: int[,]) =
А почему в мейлбоксе, а не в матрицах?

2021-10-22 18:04 UTC, AndreiZaycev commented
Добавил в тестах создание двух фолдеров, в которые записываются матрицы

2021-10-23 10:07 UTC, gsvgit approved these changes
Жуть, конечно, но ладно.

2021-10-23 16:15 UTC, merged