Homework number2 3
AndreiZaycev/Semester pull request #3
Opened 2020-10-03 11:00 UTC by AndreiZaycev

2020-10-04 13:43 UTC, gsvgit requested changes

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +    let create_array dimensionArray =
Подчёрки в именах в .NET не приняты.

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +            Array.init x1 (fun _ -> rnd.Next (1,1000)) // Для удобства рандомные числа от 1 до 1000
Для удобства чего?

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +    let Thirdtask ( array: int array )   bigelement =
Принятый способ записывать обобщённые типы: ```array<int>```.

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +            if ( array.[i] > selement ) then
А зачем пробелы справа от открывающей и слева от закрывающей скобок?

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +
Зачем столько пустых строк?

2020-10-04 13:43 UTC, gsvgit commented on src/Semester/home2.3.fs
> +        let rec Task7 n =
Так а какая это в итоге домашка сейчас сдаётся? Я просил: оди реквест --- одна домашка

2020-10-04 13:43 UTC, gsvgit commented on tests/Semester.Tests/Tests.fs
>      testList "samples"
Не сваливайте все тесты в одну кучу. Разбейте из на группы. Хотя бы по задачам.

2020-10-13 06:38 UTC, gsvgit requested changes

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/Main.fs
> +             printfn ("Введите размерность массива:")
Размерность ли? Может всё же размер?

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/Main.fs
> +        | Ftask of x: float
А почему что-то Вы принимаете как аргумент командной строки, а что-то просите ввести пользователя в интерактивном режиме. В чём разница?

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/hometaskNumberTwo.fs
> +    let Thirdtask (array: int array)   bigelement =
Лишние пробелы между параметрами

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/hometaskNumberTwo.fs
> +        if felement > selement
А почему Вы то then на новую строку переносите, то на то же, что и  if оставляете?

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/hometaskNumberTwo.fs
> +            if (array.[i] > selement) then
А зачем скобки вокруг условия?

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/hometaskNumberTwo.fs
> +        array.[z] <- array.[z] + array.[v]
А правда, что индексы всегда в "хорошем" диапазоне?

2020-10-13 06:38 UTC, gsvgit commented on src/Semester/hometaskNumberTwo.fs
> +
И зачем столько лишних переводов строк в конце?

2020-10-13 19:06 UTC, AndreiZaycev commented on src/Semester/hometaskNumberTwo.fs
> +            if (array.[i] > selement) then
Вредная привычка)

2020-10-13 19:07 UTC, AndreiZaycev commented on src/Semester/hometaskNumberTwo.fs
> +        array.[z] <- array.[z] + array.[v]
Нет, исправлю

2020-10-14 07:05 UTC, AndreiZaycev commented on src/Semester/Main.fs
> +        | Ftask of x: float
Я решил попробовать и тот, и тот способ

2020-10-15 07:50 UTC, gsvgit reviewed
Ок.

2020-10-15 07:50 UTC, gsvgit approved these changes
Ок.

2020-10-15 13:23 UTC, merged