Homework 3
AndreiZaycev/Semester pull request #4
Opened 2020-10-15 19:48 UTC by AndreiZaycev

Homework 3 done

2020-10-16 06:40 UTC, gsvgit requested changes
Первые 2 ок, остальное надо дорабатывать.

2020-10-16 06:40 UTC, gsvgit commented on src/Semester/homework3.fs
> +            let a = [|0 .. t|]
А можно ли как-то меньше дополнительной памяти использовать?

2020-10-16 06:40 UTC, gsvgit commented on src/Semester/homework3.fs
> +            then a.[i] <- 0
Нулевой элемент у Вас и так всегда нулём инициализируется, так что это излишне. Как, впрочем, и первый единицей.

2020-10-16 06:40 UTC, gsvgit commented on src/Semester/homework3.fs
> +        then failwith "Matrix needs to be square"
Вообще, умножать можно не только квадратные матрицы. А вот в степень возводить, да, квадратные.

2020-10-16 06:40 UTC, gsvgit commented on src/Semester/homework3.fs
> +            else
А что Вы постеснялись и else в одну строку записать?

2020-10-16 06:40 UTC, gsvgit commented on src/Semester/homework3.fs
> +    let powMatrix (e: int [] []) x =
А почему Вы в предыдущей функции не использовали степень?

2020-10-16 06:41 UTC, gsvgit commented
Извините, 1 и 3, а не первые два.

2020-10-16 07:06 UTC, AndreiZaycev commented on src/Semester/homework3.fs
> +    let powMatrix (e: int [] []) x =
А с task11 есть проблемы?

2020-10-16 07:11 UTC, gsvgit requested changes

2020-10-16 07:11 UTC, gsvgit commented on src/Semester/homework3.fs
> +                then
А почему тут тоже не на одной строке то, что под then и else?

2020-10-16 07:11 UTC, gsvgit commented on src/Semester/homework3.fs
> +    let powMatrix (e: int [] []) x =
Разве что с форматированием.

2020-10-16 07:13 UTC, AndreiZaycev commented on src/Semester/homework3.fs
> +    let powMatrix (e: int [] []) x =
Ок

2020-10-16 07:14 UTC, AndreiZaycev commented on src/Semester/homework3.fs
> +            then a.[i] <- 0
Ух ты! Я не знал, исправлю

2020-10-16 07:17 UTC, AndreiZaycev commented on src/Semester/homework3.fs
> +                then
Уберу

2020-10-22 08:03 UTC, gsvgit requested changes

2020-10-22 08:03 UTC, gsvgit commented on src/Semester/homework3.fs
> +        let I = o.Length
А правда ли, что размеры матриц всегда "правильные"?

2020-10-22 08:03 UTC, gsvgit commented on src/Semester/homework3.fs
> +    let Matrixpow0 x =
А почему какие-то фнкции нзываются с маленькой буквы, а какие-то с большой?

2020-10-25 10:22 UTC, gsvgit approved these changes
В паре мест пробелы потеряли.

2020-10-25 10:22 UTC, gsvgit commented on src/Semester/homework3.fs
> +            for i = 0 to x-2 do
Пробелы.

2020-10-25 10:47 UTC, AndreiZaycev commented on src/Semester/homework3.fs
> +            for i = 0 to x-2 do
Oops.

2020-10-28 17:48 UTC, merged