Homework#4 done
AndreiZaycev/Semester pull request #6
Opened 2020-10-30 20:20 UTC by AndreiZaycev

2020-11-03 06:28 UTC, gsvgit requested changes

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +    let Write file where =
```where``` --- это, как-бы, "где". Что в данном контексте значит такое имя переменной?

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +    let WriteArray file (x: array<int>) =
Всё же добавляйте пустую строку между объявлениями функций. Проже читать будет.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +    let WriteList file (x: list<int>) =
Забавно, что Вам проще написать кучу похожего кода, чем один раз написать предобразовалку масиива в лист и наоборот и пользоваться ей в нескольких местах. Это если Вы не знаете о том, что такие функции уже существуют. Partition Вы нашли, а эти функции нет --- старнно.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +        let mutable k = x
Зачем это? У Вас и так уже рекурсия. Можно обойтисб без мутабельных переменных. И вообще, мутабельные списки --- это злодейство какое-то.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +    let QuickSortList (file: list<int>) =
То есть файл --- это список. Очень странно.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +           QuickList left @ [pivot] @ QuickList right
А зачем сперва делать спсок из одного элемента, а потом его добавлять как голову?

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +        Divide x       // В общем я не особо понимаю какой из них является квик сортом поэтому оставлю оба))
По секрету --- ни одна из них не является тем, что нужно было реализовать.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +    let QuickArraySort2 (x: array<int>) =
Давайте оставим эти два варианта для сравнения в следующей домашке и рещё реализуем вариант, который не выделает так агрессивно новую память.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +            Array.append (Array.append (left |> _go) pivot) (right |> _go)
Вот здесь пайп прямо очень-очень нужен.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +        else ((int64 x <<< 32) + 4294967296L) + int64 y
А что это за магическая константа?

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Homework4.fs
> +        let a = x |> int16
И вот здесь пайп очень сильно нужен.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Main.fs
> +        let SortFunction _function =
У Вас две практически ижентичные функции. Это дело можно ещё упростить.

2020-11-03 06:28 UTC, gsvgit commented on src/Sorting/Main.fs
> +            printfn ("Введите два числа")
Не-не-не. Я хочу отдельно уметь запаковывать и отдельно распаковывать.

2020-11-03 06:28 UTC, gsvgit commented on tests/Sorting.Tests/TestsSortingsAndPacking.fs
> +let Testings fun1 fun2 (msg: string) =
Правда ли нато ```msg``` тип указывать?

2020-11-03 06:28 UTC, gsvgit commented on tests/Sorting.Tests/TestsSortingsAndPacking.fs
> +        [
Я бы ещё на всякий случай наоборот проверил: если даём 64 бита, то распаковка-запакаовка тоже id.

2020-11-03 06:28 UTC, gsvgit commented on tests/Sorting.Tests/TestsSortingsAndPacking.fs
> +        testProperty "16 to 64"
И тут тоже.

2020-11-04 09:27 UTC, AndreiZaycev commented on src/Sorting/Homework4.fs
> +    let WriteList file (x: list<int>) =
Так я просто думал, что вообще лучше в этой домашке не юзать Array.ofList и List.ofArray, ну если вы говорите, что можно, то переделаю

2020-11-04 09:31 UTC, AndreiZaycev commented on src/Sorting/Homework4.fs
> +        else ((int64 x <<< 32) + 4294967296L) + int64 y
2^32

2020-11-07 16:53 UTC, gsvgit approved these changes
Да, последний вариант похож на то, что хотелось увидеть.
1) В F# принято функции именовать с маленькой буквы.
2) Старайтесь всё же не указывать типы, там гже в этом нет необходимости.

2020-11-07 17:08 UTC, merged