hw 6
AndreiZaycev/Semester pull request #8
Opened 2020-11-26 15:05 UTC by AndreiZaycev

2020-11-26 16:17 UTC, gsvgit requested changes

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +    open System
Не надо содержимое модуля лишним табом отбивать.

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +        type Pair =
И декларации типов тоже не надо

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +            val lst: list<Pair>
Названия полей ничего не говорят в контексте матрицы.

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +            mtrx Почему это считывание хуже чем с фолдами? *)
Не то что хуже, просто на понятных вещах учимся работать с новыми абстракциями.

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +    let multiply (o: int[,]) (t: int[,]) =
По идее для тестовых функций место в тестовом проекте.

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/Main.fs
> +                    printfn ("\n %A") u
Много где лишние скобки у принтов.

2020-11-26 16:17 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +           testCase "Pustoi massiv"
Translit --- nashe vsio!!!

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +        let I = Array2D.length2 o
И опять переменные и функции с большой буквы называются.

2020-11-26 16:17 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
А почему Вы сразу матрицу не превращаете в булеву, а таскаете инты? Почему плотная --- понятно. Почему инты --- нет.

2020-11-27 07:52 UTC, gsvgit requested changes

2020-11-27 07:52 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +        val rows: int
Всё ещё странные имена полей

2020-11-27 07:52 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +                        k <- k + 1
Ну и комментарии такого кода можно удалить. В истории в Гите они всё равно остались)

2020-11-27 07:52 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +        val x: int<Row>
Декларации типов не надо отодвигать табами

2020-11-27 07:52 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +[<Measure>] type Row
Лучше бы перевод строки добавить после open-ов.

2020-11-27 07:52 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +        if x.Length = 0
Всё еще не понимаю, почему инты.

2020-11-27 07:52 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +let readMatrixForTests file =
Что-то у Вас слишком много читалок. Их нельзя как-то обобщить?

2020-11-27 11:14 UTC, AndreiZaycev commented on src/BoolMatrix/BoolMatrix.fs
> +        if x.Length = 0
ой блин забыл удалить)

2020-11-30 09:20 UTC, gsvgit requested changes

2020-11-30 09:20 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +    val lst: list<Pair>
Что такое ```lst``` в контексте матриц?

2020-11-30 09:20 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +let multiply (o: int[,]) (t: int[,]) =
Мне кажется, или у Вас в одной из предыдущих домашек уже было умножение целочисленных матриц реализовано. Почему бы его не использовать.

2020-11-30 09:20 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
И всё же, почему вы интовые матрицы упорно называете булевыми?

2020-11-30 10:50 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
Я интовую матрицу называю Стандартной и превращаю в булевую вроде тут

2020-11-30 10:55 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +let multiply (o: int[,]) (t: int[,]) =
Дело в том что у меня в той домашке используются типы array<array<int>> а здесь я работаю с int[,] и поэтому пришлось написать почти то же самое

2020-11-30 10:56 UTC, AndreiZaycev commented on src/BoolMatrix/BoolMatrix.fs
> +    val lst: list<Pair>
у меня тип матрица хранит сколько строк сколько столбцов и лист пар координат

2020-11-30 10:57 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
Уф. Тут да. Я просто не понимаю, почему у Вас вообще на верхний уровень всплывают интовые матрицы. Казалось бы, прочитал, туту же построил правильную будеву и всё, инты вообще ни кто и ни где не видел.

2020-11-30 11:00 UTC, AndreiZaycev commented on src/BoolMatrix/BoolMatrix.fs
> +    val lst: list<Pair>
это кстати и есть булева матрица, в которую я превращаю(не знаю почему я так решил назвать)

2020-11-30 11:06 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
Дело в том, что я тут решил не считывать с файла матрицы, а просто генерировать самому. Так бы пришлось писать считывалку для обычной матрицы потом еще проверять эквивалентность... Долго в общем

2020-12-01 09:26 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
Так и генератор можно же сразу для булевых написать.

2020-12-01 09:26 UTC, gsvgit commented on tests/BoolMatrixForTest.Tests/test.fs
> +let multiply (o: int[,]) (t: int[,]) =
А правда, что конвертация одного в другое не может быть легко сделана?

2020-12-01 12:13 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
так я это и написал у меня создается кортежик в функции generateRandomBoolMatrix который первым выдает обычную матрицу а вторым булеву

2020-12-01 12:13 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
и мне тем самым удобно тестики писать

2020-12-01 12:14 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +    let createBoolMatrixFromStandart (x: int[,]) =
Правда название неподобающее, извините :((

2020-12-01 14:20 UTC, AndreiZaycev commented on tests/BoolMatrixForTest.Tests/test.fs
> +let multiply (o: int[,]) (t: int[,]) =
а вот не знаю не пытался)

2020-12-02 12:21 UTC, gsvgit commented on src/BoolMatrix/BoolMatrix.fs
> +    val lst: list<Pair>
А-а-а-а!) Назовите чуть более вменяемо. ```notEmptyCells```, ```notEmptyData```, просто ```Data``` на худой конец.

2020-12-02 12:48 UTC, AndreiZaycev commented on src/BoolMatrix/BoolMatrix.fs
> +    val lst: list<Pair>
Хорошо)

2020-12-02 13:17 UTC, gsvgit approved these changes

2020-12-02 13:35 UTC, merged