Homework7
AndreiZaycev/Semester pull request #9
Opened 2020-12-02 18:24 UTC by AndreiZaycev

2020-12-02 20:07 UTC, gsvgit requested changes
Кроме моих замечаний, обратите внимаени ещё и на замечания от сервера. Фукнции с его замечаниями я не проверял.

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +type MyTree<'t> =
Что-то Вы тут нахитрили. То ли типовой парамер забыли, то ли ещё что. Я не понял, что Вы этим хотели сказать

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +let length x =
Но длину же через fold можно выразить.

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +let generatorMyList t =
Посмотрите, как у стандартных коддекций функции называются. Зачем этот странный суффикс везде?

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +type MyTree<'t> =
Вообще, для дерева и для списка неплохо бы разные можули и файлы завести. Зачем всё в одну кучу мешать.

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +    if length x < 1 || length y < 1
А такое бывает?

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +    if length x < 1 || length y < 1
А где тип строки?

2020-12-02 20:07 UTC, gsvgit commented on src/MyList/Listik.fs
> +        let rec concat (x: MyString) (y: MyString): MyString =
И зачем конкатенацию ещё раз писать?

2020-12-03 10:51 UTC, gsvgit requested changes
Читайте внимательно замечание к предыдущему реквесту. И -1 Вам в воспистальеных целях.

2020-12-07 14:16 UTC, gsvgit requested changes

2020-12-07 14:16 UTC, gsvgit commented on src/MyList/Main.fs
> +    | FuncToMyList
Мне казалось, или я говорил (и много раз), что не нужен здесь интерфейс командной строки. Вы прочто библиотеку создаёте.

2020-12-07 14:16 UTC, gsvgit commented on src/MyList/Tree.fs
> +    let rec _go acc x =
А правда ли, что эти все обходы не могут быть выражены через одну абстрактную обходилку?

2020-12-07 14:16 UTC, gsvgit commented on tests/MyList.Tests/exeTest.fs
> +            testProperty "check sort"
А почему бы и iter и другое таким же образом не протестировать?

2020-12-08 12:18 UTC, gsvgit requested changes

2020-12-08 12:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +        let rec _go acc x =
Что-то это сильно похоже на fold

2020-12-08 12:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +    let rec _go x y =
Зачем вложенная функция

2020-12-08 12:18 UTC, gsvgit commented on src/MyList/Listik.fs
> +    let rec _go acc x =
Думается, это можно выразить через случайный обычеый список и конвертацию его в Ваш

2020-12-08 12:49 UTC, AndreiZaycev commented on src/MyList/Listik.fs
> +    let rec _go acc x =
А так некрасиво?)

2020-12-12 10:54 UTC, gsvgit approved these changes

2020-12-12 10:54 UTC, gsvgit commented on src/MyList/Tree.fs
> +    fold (fun acc1 elem -> acc1 + elem) 0 x / fold (fun acc1 elem -> acc1 + 1) 0 x
Хех. Всё равно за два прохода по дереву. А можете за один?

2020-12-12 11:02 UTC, AndreiZaycev commented on src/MyList/Tree.fs
> +    fold (fun acc1 elem -> acc1 + elem) 0 x / fold (fun acc1 elem -> acc1 + 1) 0 x
Конечно могу! Попозже сделаю

2020-12-28 11:59 UTC, merged